# Generated by Django 5.2.7 on 2025-11-06 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_alter_useranswer_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useranswer',
            options={'verbose_name': 'پاسخ کاربر', 'verbose_name_plural': 'پاسخ\u200cهای کاربران'},
        ),
    ]
